name: test

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: kernel-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    steps:
      - name: Checkout (ringan)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          filter: blob:none
          submodules: false

      - name: Optimasi git
        run: |
          git config --global protocol.version 2
          git config --global core.compression 0

      - name: Apply patch
        run: |
          git apply --check patch/test.patch
          git apply patch/test.patch
